# Generated by Django 5.2.1 on 2025-11-12 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SafetyTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('safety_date', models.DateField(verbose_name='Select Date')),
                ('safety_type', models.CharField(choices=[('incident', 'INCIDENT'), ('accident', 'ACCIDENT')], max_length=50)),
                ('safety_description', models.TextField(verbose_name='Description of Occurrence')),
            ],
        ),
    ]
