# Generated by Django 5.2.1 on 2025-11-19 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safety', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='safetytime',
            name='safety_date',
            field=models.DateTimeField(verbose_name='Select Date & Time'),
        ),
        migrations.AlterField(
            model_name='safetytime',
            name='safety_type',
            field=models.CharField(choices=[('incident', 'INCIDENT'), ('accident', 'ACCIDENT'), ('sop', 'SOP')], max_length=50),
        ),
    ]
