# Generated by Django 5.2.1 on 2025-05-28 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarisInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('employee', models.CharField(max_length=100)),
                ('shift', models.CharField(max_length=20)),
                ('main_data', models.JSONField()),
                ('stop_times', models.JSONField(blank=True, null=True)),
                ('problems', models.JSONField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
