# Generated by Django 5.2.1 on 2025-12-26 12:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0006_alter_marisinput_employee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marisinput',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': 'Maris Production Entry'},
        ),
        migrations.RemoveField(
            model_name='marisinput',
            name='mainData',
        ),
        migrations.RemoveField(
            model_name='marisinput',
            name='problems',
        ),
        migrations.RemoveField(
            model_name='marisinput',
            name='stopTimes',
        ),
        migrations.AddField(
            model_name='marisinput',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marisinput',
            name='production_data',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='marisinput',
            name='stop_time_data',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='marisinput',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='marisinput',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='marisinput',
            name='employee',
            field=models.CharField(db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='marisinput',
            name='shift',
            field=models.CharField(choices=[('DAY', 'Day Shift'), ('NIGHT', 'Night Shift')], db_index=True, default='DAY', max_length=10),
        ),
    ]
