# Generated by Django 5.2.1 on 2025-12-31 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0007_alter_marisinput_options_remove_marisinput_maindata_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaggingInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True)),
                ('shift', models.CharField(choices=[('DAY', 'Day Shift'), ('NIGHT', 'Night Shift')], db_index=True, default='DAY', max_length=50)),
                ('employee', models.CharField(db_index=True, max_length=100, null=True)),
                ('production_data', models.JSONField(blank=True, default=list)),
                ('employee_2', models.CharField(db_index=True, max_length=100, null=True)),
                ('lot_number', models.CharField(db_index=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Bagging Production Entry',
                'ordering': ['-date', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MetalInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True)),
                ('shift', models.CharField(choices=[('DAY', 'Day Shift'), ('NIGHT', 'Night Shift')], db_index=True, default='DAY', max_length=50)),
                ('employee', models.CharField(db_index=True, max_length=100, null=True)),
                ('production_data', models.JSONField(blank=True, default=list)),
                ('lot_number', models.CharField(db_index=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Metal Production Entry',
                'ordering': ['-date', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='marisinput',
            name='problem_data',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='marisinput',
            name='shift',
            field=models.CharField(choices=[('DAY', 'Day Shift'), ('NIGHT', 'Night Shift')], db_index=True, default='DAY', max_length=50),
        ),
    ]
