# Generated by Django 5.2.1 on 2026-03-15 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0008_bagginginput_metalinput_marisinput_problem_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bagginginput',
            name='employee',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bagginginput',
            name='production_data',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='bagginginput',
            name='shift',
            field=models.CharField(choices=[('Day', 'Day'), ('Night', 'Night')], db_index=True, default='Day', max_length=50),
        ),
        migrations.AlterField(
            model_name='marisinput',
            name='employee',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='marisinput',
            name='production_data',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='marisinput',
            name='shift',
            field=models.CharField(choices=[('Day', 'Day'), ('Night', 'Night')], db_index=True, default='Day', max_length=50),
        ),
        migrations.AlterField(
            model_name='metalinput',
            name='employee',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='metalinput',
            name='production_data',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='metalinput',
            name='shift',
            field=models.CharField(choices=[('Day', 'Day'), ('Night', 'Night')], db_index=True, default='Day', max_length=50),
        ),
    ]
