# Generated by Django 5.2.1 on 2026-04-27 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0009_alter_bagginginput_employee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bagginginput',
            name='lot_number',
            field=models.CharField(db_index=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='MarisDailySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('employee', models.CharField(db_index=True, max_length=100)),
                ('prod', models.FloatField(default=0)),
                ('scrap', models.FloatField(default=0)),
                ('dlnc', models.FloatField(default=0)),
                ('reject', models.FloatField(default=0)),
                ('screen', models.FloatField(default=0)),
                ('visslab', models.FloatField(default=0)),
                ('stop_hr', models.FloatField(default=0)),
                ('off_hours', models.FloatField(default=0)),
                ('mech_hr', models.FloatField(default=0)),
                ('order_chg', models.IntegerField(default=0)),
                ('mech_fail', models.IntegerField(default=0)),
                ('num_shifts', models.IntegerField(default=0)),
            ],
            options={
                'unique_together': {('date', 'employee')},
            },
        ),
    ]
