# Generated by Django 5.2.1 on 2026-05-08 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0010_alter_bagginginput_lot_number_marisdailysummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='marisdailysummary',
            name='output_setting',
            field=models.FloatField(default=0),
        ),
    ]
