# Generated by Django 5.2.1 on 2026-05-10 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0011_marisdailysummary_output_setting'),
    ]

    operations = [
        migrations.AddField(
            model_name='marisdailysummary',
            name='perfect_time',
            field=models.FloatField(default=0),
        ),
    ]
