# Generated by Django 5.2.1 on 2025-12-04 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemcode', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcode',
            name='item_type',
            field=models.CharField(choices=[('nvl', 'NVL'), ('tp', 'TP'), ('semi-tp', 'SEMI-TP'), ('shaker', 'SHAKER')], max_length=100),
        ),
    ]
