# Generated by Django 5.2.1 on 2025-05-28 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marisinput',
            name='main_data',
            field=models.CharField(max_length=100),
        ),
    ]
