# Generated by Django 5.2.1 on 2025-05-28 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0002_alter_marisinput_main_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marisinput',
            name='main_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
