# Generated by Django 5.2.1 on 2025-05-29 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0004_alter_marisinput_main_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marisinput',
            old_name='main_data',
            new_name='mainData',
        ),
        migrations.RenameField(
            model_name='marisinput',
            old_name='stop_times',
            new_name='stopTimes',
        ),
    ]
