# Generated by Django 5.2.1 on 2025-09-11 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0005_rename_main_data_marisinput_maindata_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marisinput',
            name='employee',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
