# Generated by Django 5.2.1 on 2025-12-04 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('item_description', models.TextField(blank=True)),
                ('item_type', models.CharField(choices=[('nvl', 'NVL'), ('tp', 'TP'), ('semi-tp', 'SEMI-TP')], max_length=100)),
            ],
        ),
    ]
