# Generated by Django 5.2.1 on 2025-12-25 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemcode', '0002_alter_itemcode_item_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcode',
            name='item_type',
            field=models.CharField(choices=[('tp', 'TP'), ('semi-tp', 'SEMI-TP')], max_length=100),
        ),
    ]
